# Generated by Django 5.1.4 on 2025-03-07 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_registration1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=122)),
                ('phone', models.CharField(max_length=10)),
                ('service_plan', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=200)),
                ('address2', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=100)),
                ('plants', models.CharField(max_length=100)),
            ],
        ),
    ]
