# Generated by Django 5.1.4 on 2025-03-07 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_book_service'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book_service',
            new_name='Book_service1',
        ),
    ]
