# Generated by Django 5.1.4 on 2025-03-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_rename_book_service_book_service1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_service1',
            name='service_plan',
            field=models.IntegerField(choices=[(1, 'yearly'), (2, 'monthly'), (3, 'weekly'), (4, 'daily')], max_length=100),
        ),
    ]
