# Generated by Django 5.1.4 on 2025-03-29 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_book_service1_service_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book_service1',
            name='service_plan',
        ),
    ]
