# Generated by Django 5.1.4 on 2025-03-29 18:22

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_remove_book_service1_service_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_service1',
            name='service_plan',
            field=models.IntegerField(choices=[(1, 'yearly'), (2, 'monthly'), (3, 'weekly'), (4, 'daily')], default=django.utils.timezone.now, max_length=100),
            preserve_default=False,
        ),
    ]
