# Generated by Django 5.1.4 on 2025-04-10 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_passwordreset'),
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('price', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.RenameField(
            model_name='book_service1',
            old_name='area',
            new_name='User_name',
        ),
        migrations.RenameField(
            model_name='book_service1',
            old_name='address2',
            new_name='service_details',
        ),
        migrations.RemoveField(
            model_name='book_service1',
            name='email',
        ),
        migrations.RemoveField(
            model_name='book_service1',
            name='name',
        ),
        migrations.RemoveField(
            model_name='book_service1',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='book_service1',
            name='plants',
        ),
        migrations.AddField(
            model_name='book_service1',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='book_service1',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='book_service1',
            name='service_plan',
            field=models.CharField(max_length=100),
        ),
        migrations.DeleteModel(
            name='PasswordReset',
        ),
    ]
