# Generated by Django 5.1.4 on 2025-04-10 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_items_plant_rename_area_book_service1_user_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='servcie_plan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('service_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('service_details', models.CharField(max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='book_service1',
            name='price',
        ),
        migrations.RemoveField(
            model_name='book_service1',
            name='service_details',
        ),
    ]
