# Generated by Django 5.1.4 on 2025-04-16 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_servcie_plan_remove_book_service1_price_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='servcie_plan',
            new_name='service_plan',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='Name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='book_service1',
            name='service_plan',
        ),
    ]
