# Generated by Django 5.1.4 on 2025-04-17 03:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_rename_servcie_plan_service_plan_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plant',
            old_name='Name',
            new_name='name',
        ),
    ]
