# Generated by Django 5.1.4 on 2025-04-17 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_rename_name_plant_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='service_plan',
        ),
    ]
