# Generated by Django 5.1.4 on 2025-04-18 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_remove_service_id_service_service_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicebooking',
            name='id',
        ),
        migrations.AddField(
            model_name='servicebooking',
            name='booking_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
