# Generated by Django 5.1.4 on 2025-04-18 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_remove_servicebooking_id_servicebooking_booking_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicebooking',
            old_name='address',
            new_name='address1',
        ),
    ]
