# Generated by Django 5.1.4 on 2025-04-18 07:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_rename_address_servicebooking_address1'),
    ]

    operations = [
        migrations.CreateModel(
            name='P_Type',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('t_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='plant',
            name='category',
        ),
        migrations.AlterField(
            model_name='plant',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.p_type'),
        ),
    ]
