# Generated by Django 5.1.4 on 2025-04-18 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_p_type_remove_plant_category_alter_plant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='type',
            field=models.CharField(choices=[('aquatic', 'Aquatic Plants'), ('medicinal', 'Medicinal'), ('flowering', 'Flowering'), ('indoor', 'Inddor'), ('climbers', 'Climbers'), ('fruit_bearing', 'Fruit Bearing')], max_length=50),
        ),
    ]
