# Generated by Django 5.1.4 on 2025-04-18 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_alter_plant_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(default='static\\images\x08eautiful-park.jpg', upload_to='images/'),
        ),
    ]
