# Generated by Django 5.1.4 on 2025-04-18 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0021_alter_plant_description_alter_plant_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(default='static\\images\x08eautiful-park.jpg', upload_to='media/images/'),
        ),
    ]
