# Generated by Django 5.1.4 on 2025-04-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_alter_plant_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='items',
            name='category',
        ),
        migrations.RemoveField(
            model_name='items',
            name='type',
        ),
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/'),
        ),
    ]
